version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: my-sql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: myadmin1
    environment:
      PMA_HOST: db
      PMA_PASSWORD: 12345678
    ports:
      - "8081:80"
